# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample_bind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.FloatField(verbose_name='Multiple_Risk')),
                ('muta_rate', models.FloatField(verbose_name='Mutation rate')),
                ('hgb', models.FloatField(verbose_name='HGB')),
                ('explanation', models.TextField()),
                ('bind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample_bind.Bind', verbose_name='Sample code')),
            ],
            options={
                'verbose_name_plural': 'reports',
                'verbose_name': 'report',
            },
        ),
    ]
