# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 05:45
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='explanation',
            field=mezzanine.core.fields.RichTextField(verbose_name='Explanation'),
        ),
    ]
